package writer

import (
	"crypto/sha256"
	"fmt"
	"log/slog"
	"os"
	"path/filepath"
	"sync"

	"github.com/jkaninda/goma-k8s-provider/internal/converter"
	"gopkg.in/yaml.v3"
)

const outputFile = "goma.yaml"

// Writer writes ConfigBundle YAML files atomically with checksum dedup.
type Writer struct {
	dir      string
	mu       sync.Mutex
	lastHash string
}

// New creates a new Writer targeting the given directory.
func New(dir string) *Writer {
	return &Writer{dir: dir}
}

// Write marshals the bundle to YAML and writes it to the output directory.
// It skips the write if the checksum matches the last write.
func (w *Writer) Write(bundle converter.ConfigBundle) error {
	data, err := yaml.Marshal(bundle)
	if err != nil {
		return fmt.Errorf("failed to marshal config bundle: %w", err)
	}

	header := []byte("# Goma Gateway configuration — generated by goma-k8s-provider\n# DO NOT EDIT MANUALLY\n\n")
	content := append(header, data...)

	hash := fmt.Sprintf("%x", sha256.Sum256(content))

	w.mu.Lock()
	defer w.mu.Unlock()

	if hash == w.lastHash {
		slog.Debug("Config unchanged, skipping write", "checksum", hash[:12])
		return nil
	}

	// Ensure directory exists
	if err := os.MkdirAll(w.dir, 0755); err != nil {
		return fmt.Errorf("failed to create output directory: %w", err)
	}

	// Atomic write: write to temp file then rename
	target := filepath.Join(w.dir, outputFile)
	tmp := target + ".tmp"

	if err := os.WriteFile(tmp, content, 0644); err != nil {
		return fmt.Errorf("failed to write temp file: %w", err)
	}

	if err := os.Rename(tmp, target); err != nil {
		_ = os.Remove(tmp)
		return fmt.Errorf("failed to rename temp file: %w", err)
	}

	w.lastHash = hash
	slog.Info("Config written",
		"path", target,
		"routes", len(bundle.Routes),
		"middlewares", len(bundle.Middlewares),
		"checksum", hash[:12],
	)

	return nil
}
